alias gophertrain="cd ~/src/github.com/gophertrain"
alias bketelsen="cd ~/src/github.com/bketelsen"
alias gophercon="cd ~/src/github.com/gophercon"
alias gopheracademy="cd ~/src/github.com/gopheracademy"
alias tmux="tmux -2"
